version: "3.8"

services:
  mongo-test:
    image: mongo:latest
    container_name: "mongo-test"
    ports:
      - 27018:27017
    networks:
      - app-network

  product-service:
    image: product-service:1.0
    container_name: "product-service"
    ports:
      - 9090:9090
    environment:
      - MONGO_URI=mongodb://mongo-test:27017/productDb
    depends_on:
      - mongo-test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
